spring:
  application:
    name: config-client
  cloud:
    config:
      # uri: http://localhost:9500
      fail-fast: true
      discovery:
        service-id: config-server
        enabled: true
  profiles:
    active: dev

  rabbitmq:
    host: http://119.23.228.243
    username: admin
    password: rabbitforliwenchao2791372
    port: 5762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka
server:
  port: 9501
